### PR TITLE
fix 🐛(backend): ignore but print error, allow to preprovision urls.yml

### PR DESCRIPTION
**Pull request by Banh-Canh**
Hello, i'm using nixos and i'd like to preprovision the urls.yaml and make it read-only.

I modfied the function to allow that by ignoring the error as it would otherwise continue and save to cache read data.

I'm willing to look for another way in term of UX if you want to or I will just keep this custom :)

### CODE REVIEW

**Comment by TypicalAM** [comment]
Hi! It would be better if this behaviour were to be a flag, like `--readonly_config`, since the only scenario in which this isn't a critical error is using nix with something like `home-manager`. Also please use `log.Println` instead of `fmt`, because we are logging to a file and a `fmt.Println` always shows the line after we close `goread`:

https://github.com/TypicalAM/goread/blob/17d8570aa804a7ac483a2e0718dc6172aa4abae1/cmd/goread/goread.go#L81

**Comment by Banh-Canh** [comment]
> Hi! It would be better if this behaviour were to be a flag, like `--readonly_config`, since the only scenario in which this isn't a critical error is using nix with something like `home-manager`. Also please use `log.Println` instead of `fmt`, because we are logging to a file and a `fmt.Println` always shows the line after we close `goread`:
> 
> https://github.com/TypicalAM/goread/blob/17d8570aa804a7ac483a2e0718dc6172aa4abae1/cmd/goread/goread.go#L81

as requested, i added a flag instead, let me know if there is anything else

**Comment by TypicalAM** [comment]
`git rebase -i HEAD~2 && git push -f` to conform previous commit msgs (`feat: xyz` not `feat 🐬:` although I do appreciate the flair). Also `--urls_readonly` makes more sense to me now that I've looked at the flags.

**Comment by Banh-Canh** [comment]
And here it is ! It was just some conventional commit (scope) + some fancy emoji (hehe), and i splitted the commit intentionnaly for readability ! I get what you mean tho so it's corrected

**Comment by TypicalAM** [comment]
Nice! Thank you

**Pull request merged**
